cluster: "uge_submit.py"
cluster-status: "uge_status.py"
jobscript: "uge_jobscript.sh"
local-cores: 1
latency-wait: "{{cookiecutter.latency_wait}}"
use-conda: "{{cookiecutter.use_conda}}"
use-singularity: "{{cookiecutter.use_singularity}}"
keep-going: "{{cookiecutter.keep_going}}"
restart-times: "{{cookiecutter.restart_times}}"
jobs: "{{cookiecutter.jobs}}"
printshellcmds: "{{cookiecutter.print_shell_commands}}"
max-jobs-per-second: "{{cookiecutter.max_jobs_per_second}}"
max-status-checks-per-second: "{{cookiecutter.max_status_checks_per_second}}"
